# Generated by Django 2.2.7 on 2020-01-10 22:12

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='classroom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=30, unique=True)),
                ('class_description', models.CharField(max_length=100)),
                ('class_type', models.CharField(max_length=15)),
                ('class_location', models.CharField(max_length=255)),
                ('class_capacity', models.IntegerField(default=0)),
                ('class_last_updated', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=30, unique=True)),
                ('course_description', models.CharField(max_length=100)),
                ('course_type', models.CharField(default='Lecture', max_length=15)),
                ('course_notes', models.CharField(default='MS Office', max_length=200)),
                ('course_last_updated', models.DateTimeField(auto_now_add=True)),
                ('course_clsroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classrm', to='maintain.classroom')),
                ('course_instructor', models.ManyToManyField(related_name='course_ins', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sch_day', models.CharField(choices=[('MON', 'Monday'), ('TUE', 'Tuesday'), ('WED', 'Wednesday'), ('THU', 'Thursday'), ('FRI', 'Friday'), ('SAT', 'Saturday'), ('SUN', 'Sunday')], default='MON', max_length=3)),
                ('sch_start', models.TimeField(default=datetime.time(0, 0))),
                ('sch_end', models.TimeField(default=datetime.time(0, 0))),
                ('sch_semester', models.CharField(default='Spring 2020', max_length=40)),
                ('sch_year', models.CharField(default='2019-20', max_length=15)),
                ('sch_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_schedule', to='maintain.course')),
            ],
        ),
        migrations.CreateModel(
            name='clas_sware',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sware_name', models.CharField(max_length=30, unique=True)),
                ('sware_description', models.CharField(max_length=100)),
                ('sware_notes', models.CharField(max_length=15)),
                ('sware_last_updated', models.DateTimeField(auto_now_add=True)),
                ('sware_classroom', models.ManyToManyField(related_name='sware', to='maintain.classroom')),
            ],
        ),
        migrations.CreateModel(
            name='clas_hware',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hware_name', models.CharField(max_length=30, unique=True)),
                ('hware_description', models.CharField(max_length=100)),
                ('hware_notes', models.CharField(max_length=15)),
                ('hware_last_updated', models.DateTimeField(auto_now_add=True)),
                ('hware_classroom', models.ManyToManyField(related_name='hware', to='maintain.classroom')),
            ],
        ),
    ]
