# Generated by Django 2.2.7 on 2020-01-28 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintain', '0005_auto_20200127_1314'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_level',
            field=models.CharField(default='Graduate', max_length=15),
        ),
        migrations.AddField(
            model_name='course',
            name='sch_dateslot',
            field=models.CharField(default='2/4-5/20', max_length=12),
        ),
        migrations.AddField(
            model_name='course',
            name='sch_days',
            field=models.CharField(default='M', max_length=8),
        ),
        migrations.AddField(
            model_name='course',
            name='sch_semester',
            field=models.CharField(default='Spring 2020', max_length=40),
        ),
        migrations.AddField(
            model_name='course',
            name='sch_timeslot',
            field=models.CharField(default='1745-2100', max_length=10),
        ),
        migrations.AddField(
            model_name='course',
            name='sch_year',
            field=models.CharField(default='2019-20', max_length=15),
        ),
        migrations.RemoveField(
            model_name='course',
            name='course_clsroom',
        ),
        migrations.AddField(
            model_name='course',
            name='course_clsroom',
            field=models.ManyToManyField(related_name='classrm', to='maintain.classroom'),
        ),
        migrations.DeleteModel(
            name='schedule',
        ),
    ]
