# Generated by Django 2.2.7 on 2020-01-09 22:22

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='clas_hware',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hware_name', models.CharField(max_length=30, unique=True)),
                ('hware_description', models.CharField(max_length=100)),
                ('hware_notes', models.CharField(max_length=15)),
                ('hware_last_updated', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='clas_sware',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sware_name', models.CharField(max_length=30, unique=True)),
                ('sware_description', models.CharField(max_length=100)),
                ('sware_notes', models.CharField(max_length=15)),
                ('sware_last_updated', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='classroom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=30, unique=True)),
                ('class_description', models.CharField(max_length=100)),
                ('class_type', models.CharField(max_length=15)),
                ('class_location', models.CharField(max_length=255)),
                ('class_capacity', models.IntegerField(default=0)),
                ('class_last_updated', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=30, unique=True)),
                ('course_description', models.CharField(max_length=100)),
                ('course_type', models.CharField(max_length=15)),
                ('course_required_instr_sware', models.CharField(default='MS Office', max_length=200)),
                ('course_required_sware', models.CharField(default='MS Office', max_length=200)),
                ('course_notes', models.CharField(default='MS Office', max_length=200)),
                ('course_last_updated', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sch_day', models.CharField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], max_length=1)),
                ('sch_start', models.TimeField(default=datetime.time(0, 0))),
                ('sch_end', models.TimeField(default=datetime.time(0, 0))),
                ('sch_semester', models.IntegerField(default=2020)),
                ('sch_year', models.CharField(default='2019-20', max_length=15)),
                ('sch_clsroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classrm', to='maintain.classroom')),
                ('sch_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_schedule', to='maintain.course')),
                ('sch_instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_ins', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='clas_sware_install',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classroom_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sware', to='maintain.classroom')),
                ('sware_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classware', to='maintain.clas_sware')),
            ],
        ),
        migrations.CreateModel(
            name='clas_hware_deploy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classroom_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hware', to='maintain.classroom')),
                ('hware_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clashware', to='maintain.clas_hware')),
            ],
        ),
    ]
