# Generated by Django 2.2.7 on 2020-01-09 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintain', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='course_required_instr_sware',
        ),
        migrations.RemoveField(
            model_name='course',
            name='course_required_sware',
        ),
        migrations.AlterField(
            model_name='course',
            name='course_type',
            field=models.CharField(default='Lecture', max_length=15),
        ),
    ]
