# Generated by Django 2.2.7 on 2020-01-09 23:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maintain', '0002_auto_20200109_1637'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clas_sware_install',
            old_name='classroom_id',
            new_name='classroom',
        ),
        migrations.RenameField(
            model_name='clas_sware_install',
            old_name='sware_id',
            new_name='sware',
        ),
    ]
