# Generated by Django 2.2.7 on 2020-01-10 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintain', '0003_auto_20200109_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='sch_semester',
            field=models.CharField(default='Spring 2020', max_length=40),
        ),
    ]
