# Generated by Django 2.2.7 on 2020-01-10 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintain', '0004_auto_20200109_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='sch_day',
            field=models.CharField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], default=0, max_length=20),
        ),
    ]
