# Generated by Django 2.2.7 on 2020-01-10 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintain', '0005_auto_20200109_1815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='sch_day',
            field=models.CharField(choices=[('MON', 'Monday'), ('TUE', 'Tuesday'), ('WED', 'Wednesday'), ('THU', 'Thursday'), ('FRI', 'Friday'), ('SAT', 'Saturday'), ('SUN', 'Sunday')], default='MON', max_length=3),
        ),
    ]
