# Generated by Django 2.2.7 on 2020-01-10 21:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('maintain', '0006_auto_20200110_1524'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='sch_clsroom',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='sch_instructor',
        ),
        migrations.AddField(
            model_name='clas_hware',
            name='hware_classroom',
            field=models.ManyToManyField(related_name='hware', to='maintain.classroom'),
        ),
        migrations.AddField(
            model_name='clas_sware',
            name='sware_classroom',
            field=models.ManyToManyField(related_name='sware', to='maintain.classroom'),
        ),
        migrations.AddField(
            model_name='course',
            name='course_clsroom',
            field=models.ForeignKey(default='OSS000', on_delete=django.db.models.deletion.CASCADE, related_name='classrm', to='maintain.classroom'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='course_instructor',
            field=models.ManyToManyField(related_name='course_ins', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='clas_hware_deploy',
            name='classroom_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hware1', to='maintain.classroom'),
        ),
        migrations.AlterField(
            model_name='clas_hware_deploy',
            name='hware_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clashware1', to='maintain.clas_hware'),
        ),
        migrations.AlterField(
            model_name='clas_sware_install',
            name='classroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sware1', to='maintain.classroom'),
        ),
        migrations.AlterField(
            model_name='clas_sware_install',
            name='sware',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classware1', to='maintain.clas_sware'),
        ),
    ]
